/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UploadImageLazyImport = createFileRoute('/upload-image')()
const SettingsLazyImport = createFileRoute('/settings')()
const ReportsLazyImport = createFileRoute('/reports')()
const InvoicesLazyImport = createFileRoute('/invoices')()
const BrowseLazyImport = createFileRoute('/browse')()
const IndexLazyImport = createFileRoute('/')()
const RequestsIndexLazyImport = createFileRoute('/requests/')()
const RequestsNewLazyImport = createFileRoute('/requests/new')()
const RequestsRequestIdLazyImport = createFileRoute('/requests/$requestId')()

// Create/Update Routes

const UploadImageLazyRoute = UploadImageLazyImport.update({
  path: '/upload-image',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/upload-image.lazy').then((d) => d.Route))

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const ReportsLazyRoute = ReportsLazyImport.update({
  path: '/reports',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/reports.lazy').then((d) => d.Route))

const InvoicesLazyRoute = InvoicesLazyImport.update({
  path: '/invoices',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/invoices.lazy').then((d) => d.Route))

const BrowseLazyRoute = BrowseLazyImport.update({
  path: '/browse',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/browse.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RequestsIndexLazyRoute = RequestsIndexLazyImport.update({
  path: '/requests/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/requests/index.lazy').then((d) => d.Route),
)

const RequestsNewLazyRoute = RequestsNewLazyImport.update({
  path: '/requests/new',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/requests/new.lazy').then((d) => d.Route))

const RequestsRequestIdLazyRoute = RequestsRequestIdLazyImport.update({
  path: '/requests/$requestId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/requests/$requestId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseLazyImport
      parentRoute: typeof rootRoute
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesLazyImport
      parentRoute: typeof rootRoute
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/upload-image': {
      id: '/upload-image'
      path: '/upload-image'
      fullPath: '/upload-image'
      preLoaderRoute: typeof UploadImageLazyImport
      parentRoute: typeof rootRoute
    }
    '/requests/$requestId': {
      id: '/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof RequestsRequestIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewLazyImport
      parentRoute: typeof rootRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  BrowseLazyRoute,
  InvoicesLazyRoute,
  ReportsLazyRoute,
  SettingsLazyRoute,
  UploadImageLazyRoute,
  RequestsRequestIdLazyRoute,
  RequestsNewLazyRoute,
  RequestsIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/browse",
        "/invoices",
        "/reports",
        "/settings",
        "/upload-image",
        "/requests/$requestId",
        "/requests/new",
        "/requests/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/browse": {
      "filePath": "browse.lazy.tsx"
    },
    "/invoices": {
      "filePath": "invoices.lazy.tsx"
    },
    "/reports": {
      "filePath": "reports.lazy.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/upload-image": {
      "filePath": "upload-image.lazy.tsx"
    },
    "/requests/$requestId": {
      "filePath": "requests/$requestId.lazy.tsx"
    },
    "/requests/new": {
      "filePath": "requests/new.lazy.tsx"
    },
    "/requests/": {
      "filePath": "requests/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
